Update gcloud-fix.yaml

diff --git a/task/gcloud/0.3/gcloud-fix.yaml b/task/gcloud/0.3/gcloud-fix.yaml
--- a/task/gcloud/0.3/gcloud-fix.yaml
+++ b/task/gcloud/0.3/gcloud-fix.yaml
@@ -32,11 +32,11 @@ spec:
     script: |
       CMD="gcloud $(params.ARGS)"
       echo -n "Executing following gcloud command: $CMD"
-      RESULT_GCLOUD="$($CMD)"
+      RESULT_GCLOUD="$($CMD 2>&1 || true)"
+      EXIT_CODE=$? # Still capture the exit code
+
       echo -n "Result"
       echo -n "$RESULT_GCLOUD" > $(results.gcloud-output.path)
-      cat $(results.gcloud-output.path)
-      exit 0
       
       # EXIT_CODE="$?"
       # if [ "$EXIT_CODE" != 0 ]
